app/home/forms.py
from flask import url_for
from flask_wtf import Form, FlaskForm
from wtforms import ValidationError
from flask_ckeditor import CKEditorField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.fields import TextAreaField, SelectMultipleField
from flask_wtf import Form
from wtforms import ValidationError
from wtforms.fields import (
    BooleanField,
    PasswordField,
    StringField,
    SubmitField,
    DateField,
    DecimalField,
    SelectField,
    HiddenField,
    IntegerField,
)
from wtforms.fields.html5 import EmailField
from wtforms.validators import Email, EqualTo, InputRequired, Length, DataRequired

from app.models import User
from app.models import *


class SearchForm(Form):
    year_from = SelectField(id="car-years_from", coerce=int)
    year_to = SelectField(id="car-years_to", coerce=int)
    make = SelectField(id="car-makes", coerce=int)
    model = SelectField(id="car-models", coerce=int)
    transmission = SelectField(choices=[], id="car-trans", coerce=int)
    fuel = SelectField(choices=[], id="car-fuel", coerce=int)
    submit = SubmitField("FIND A CAR")

    def __init__(self, *args, **kwargs):
        if "formdata" not in kwargs:
            kwargs["formdata"] = request.args
        if "csrf_enabled" not in kwargs:
            kwargs["csrf_enabled"] = False
        super(SearchForm, self).__init__(*args, **kwargs)


class BookingForm(Form):
    departure_date = DateField(
        "Check In", validators=[DataRequired()], format="%m/%d/%Y"
    )
    kids = IntegerField("Kids", validators=[DataRequired()])
    total = HiddenField(validators=[DataRequired()])
    adults = IntegerField("Adults", validators=[DataRequired()])
    book = SubmitField("BOOK NOW")


class PaymentForm(Form):
    email = StringField("Email", validators=[DataRequired()])
    card_holder_name = StringField("Card Holder Name", validators=[DataRequired()])
    card_number = StringField("Card Number", validators=[DataRequired()])
    select_card = SelectField(
        "Select Card",
        validators=[DataRequired()],
        choices=[
            ("1", "EUR 6524 1254 6212 2541"),
            ("2", "EUR 6524 1254 6212 2541"),
            ("3", "USD 1254 6524 2541 6212"),
        ],
    )
    month = SelectField(
        validators=[DataRequired()],
        choices=[
            ("jan", "January"),
            ("feb", "February"),
            ("mar", "March"),
            ("apri", "April"),
            ("may", "May"),
            ("jun", "June"),
            ("jul", "July"),
            ("aug", "August"),
            ("sep", "September"),
            ("octo", "October"),
            ("nov", "November"),
            ("dec", "December"),
        ],
    )
    years = SelectField(
        validators=[DataRequired()],
        choices=[
            ("2018", "2018"),
            ("2019", "2019"),
            ("2020", "2020"),
            ("2021", "2021"),
            ("2022", "2022"),
        ],
    )

    # card_identification_number =  StringField('Card Identification Number', validators=[DataRequired()])
    billing_zip_code = StringField("Billing Zip Code", validators=[DataRequired()])

    confirm_booking = SubmitField("Confirm Booking")


class SellVehicleForm(FlaskForm):
    plate = StringField("Plate")
    description = TextAreaField("Description")
    name = StringField("Name")
    price = StringField("Price", validators=[InputRequired()])
    mileage = StringField("Mileage", validators=[InputRequired()])
    color = StringField("Color", validators=[InputRequired()])
    condition = StringField("Condition")
    year = StringField("Year", validators=[InputRequired()])
    model = SelectField(validators=[InputRequired()], choices=[], coerce=int)
    make = SelectField(validators=[InputRequired()], choices=[], coerce=int)
    fuel_type = SelectField(choices=[], coerce=int)
    transmission = SelectField(choices=[], coerce=int)
    interior = StringField("Interior")
    engine_size = StringField("Engine Size")
    seller_email = StringField("Email", validators=[InputRequired()])
    seller_name = StringField("Name", validators=[InputRequired()])
    phone_number = StringField("Phone", validators=[InputRequired()])
    area = StringField("Area", validators=[InputRequired()])
    submit = SubmitField("Submit")


class ImportVehicleForm(FlaskForm):
    plate = StringField("Plate")
    description = TextAreaField("Description")
    name = StringField("Name")
    price = StringField("Price")
    mileage = StringField("Mileage")
    color = StringField("Color")
    condition = StringField("Condition")
    year = StringField("Year")
    model = SelectField(validators=[InputRequired()], choices=[], coerce=int)
    make = SelectField(validators=[InputRequired()], choices=[], coerce=int)
    fuel_type = SelectField(choices=[], coerce=int)
    transmission = SelectField(choices=[], coerce=int)
    interior = StringField("Interior")
    engine_size = StringField("Engine Size")
    importer_email = StringField("Email", validators=[InputRequired()])
    importer_name = StringField("Name", validators=[InputRequired()])
    phone_number = StringField("Phone", validators=[InputRequired()])
    area = StringField("Area")
    submit = SubmitField("Submit")


class ContactForm(FlaskForm):
    message = TextAreaField("message")
    email = StringField("Email", validators=[InputRequired()])
    name = StringField("Name", validators=[InputRequired()])
    phone_number = StringField("Phone", validators=[InputRequired()])
    subject = StringField("Subject")
    submit = SubmitField("Send Message")


class EnquiryForm(FlaskForm):
    message = TextAreaField("message")
    budget = StringField("budget")
    email = StringField("Email", validators=[InputRequired()])
    name = StringField("Name", validators=[InputRequired()])
    phone_number = StringField("Phone", validators=[InputRequired()])
    year = StringField("Year")
    plate = StringField("Plate")
    make = StringField()
    model = StringField()
    submit = SubmitField("Send Message")

app/home/__init__.py
from app.home.views import home  # noqa

app/home/views.py
from flask import Blueprint, render_template, redirect, url_for, jsonify, flash
from flask_login import current_user, login_required
from datetime import datetime, date
from app.models import *
from app.home.forms import *
from sqlalchemy import or_, and_, func

home = Blueprint("home", __name__)


@home.route("/", methods=["post", "get"])
def index():
    """Admin dashboard page."""
    all_vehicles = Vehicle.query.order_by(Vehicle.createdAt.desc()).limit(8)
    featured_vehicles = Vehicle.query.filter_by(featured=True).limit(8)
    form = SearchForm()
    make = [(row.id, row.name) for row in Make.query.all()]
    model = [(row.id, row.name) for row in Model.query.all()]
    transmission = [(row.id, row.type) for row in Transmission.query.all()]
    fuel = [(row.id, row.type) for row in Fuel.query.all()]
    year_to = [(i, i) for i in list(reversed(range(2000, date.today().year+1)))]
    year_from = [(i, i) for i in list(range(2000, date.today().year+1))]
    make.insert(0, (0, "--All Makes--"))
    year_from.insert(0, (0, "Year from"))
    year_to.insert(0, (0, "Year to"))
    model.insert(0, (0, "Model"))
    transmission.insert(0, (0, "Transmission"))
    fuel.insert(0, (0, "Fuel Type"))
    form.year_from.choices = year_from
    form.year_to.choices = year_to
    form.make.choices = make
    form.model.choices = model
    form.transmission.choices = transmission
    form.fuel.choices = fuel
    return render_template(
        "home/index.html",
        all_vehicles=all_vehicles,
        featured_vehicles=featured_vehicles,
        form=form,
        car_makes=Make.query.all(),
    )


@home.route("/buy_a_car", methods=["post", "get"])
def inventory():
    """all vehicles."""
    page = request.args.get("page", 1, type=int)
    year_from = request.args.get("year_from", 0, type=int)
    year_to = request.args.get("year_to", 0, type=int)
    make = request.args.get("make", 0, type=int)
    model = request.args.get("model", 0, type=int)
    fuel = request.args.get("fuel", 0, type=int)
    transmission = request.args.get("transmission", 0, type=int)
    body_type = request.args.get("body_type", "", type=str)

    makes = [(row.id, row.name) for row in Make.query.all()]
    transmissions = [(row.id, row.type) for row in Transmission.query.all()]
    fuel_types = [(row.id, row.type) for row in Fuel.query.all()]
    years = list(reversed(range(2000, date.today().year+1)))

    all_vehicles = (
        Vehicle.query.filter(
            Vehicle.year >= year_from if year_from else Vehicle.id.isnot(None)
        )
        .filter(Vehicle.year <= year_to if year_to else Vehicle.id.isnot(None))
        .filter(Vehicle.make_id == make if make else Vehicle.id.isnot(None))
        .filter(Vehicle.model_id == model if model else Vehicle.id.isnot(None))
        .filter(
            Vehicle.transmission_id == transmission
            if transmission
            else Vehicle.id.isnot(None)
        )
        .filter(Vehicle.body_type == body_type if body_type else Vehicle.id.isnot(None))
        .filter(Vehicle.fuel_type_id == fuel if fuel else Vehicle.id.isnot(None))
        .order_by(Vehicle.createdAt.desc())
        .paginate(page, current_app.config["POSTS_PER_PAGE"], False)
    )
    next_url = (
        url_for("home.inventory", page=all_vehicles.next_num)
        if all_vehicles.has_next
        else None
    )
    prev_url = (
        url_for("home.inventory", page=all_vehicles.prev_num)
        if all_vehicles.has_prev
        else None
    )
    total_vehicles = Vehicle.query.order_by(Vehicle.createdAt.desc()).all()
    vehicles_count = len(all_vehicles.items)
    max_price = int(max(node.price for node in total_vehicles)) if total_vehicles else 0
    min_price = int(min(node.price for node in total_vehicles)) if total_vehicles else 0
    return render_template(
        "home/inventory.html",
        all_vehicles=all_vehicles.items,
        vehicles_count=vehicles_count,
        next_url=next_url,
        prev_url=prev_url,
        max_price=max_price,
        min_price=min_price,
        makes=makes,
        transmissions=transmissions,
        years=years,
        fuel_types=fuel_types,
    )


@home.route("/_get_cars/", methods=["POST"])
def _get_cars():
    page = request.args.get("page", 1, type=int)
    data = request.get_json() or {}
    if (
        "years" not in data
        or "makes" not in data
        or "models" not in data
        or "bodyTypes" not in data
        or "transmissions" not in data
        or "min_price" not in data
        or "max_price" not in data
    ):
        return "", 404
    all_vehicles = (
        Vehicle.query.filter(
            Vehicle.year.in_(data["years"])
            if len(data["years"])
            else Vehicle.id.isnot(None)
        )
        .filter(
            Vehicle.make_id.in_(data["makes"])
            if len(data["makes"])
            else Vehicle.id.isnot(None)
        )
        .filter(
            Vehicle.model_id.in_(data["models"])
            if len(data["models"])
            else Vehicle.id.isnot(None)
        )
        .filter(
            Vehicle.body_type.in_(data["bodyTypes"])
            if len(data["bodyTypes"])
            else Vehicle.id.isnot(None)
        )
        .filter(
            Vehicle.transmission_id.in_(data["transmissions"])
            if len(data["transmissions"])
            else Vehicle.id.isnot(None)
        )
        .filter(
            Vehicle.price >= data["min_price"]
            if data["min_price"]
            else Vehicle.id.isnot(None)
        )
        .filter(
            Vehicle.price <= data["max_price"]
            if data["max_price"]
            else Vehicle.id.isnot(None)
        )
        .order_by(Vehicle.createdAt.desc())
        .paginate(page, current_app.config["POSTS_PER_PAGE"], False)
    )
    next_url = (
        url_for("home.inventory", page=all_vehicles.next_num)
        if all_vehicles.has_next
        else None
    )
    prev_url = (
        url_for("home.inventory", page=all_vehicles.prev_num)
        if all_vehicles.has_prev
        else None
    )
    return render_template(
        "home/_inventory.html",
        all_vehicles=all_vehicles.items,
        vehicles_count=len(all_vehicles.items),
        next_url=next_url,
        prev_url=prev_url,
    )


@home.route("/view_car/<id>", methods=["post", "get"])
def view_car(id):
    """Admin dashboard page."""
    form = EnquiryForm()
    if form.validate_on_submit():
        new_enquiry = SingleEnquiry(
            name=form.name.data,
            phone_number=form.phone_number.data,
            message=form.message.data,
            plate=form.plate.data,
            year=form.year.data,
            budget=form.budget.data,
            make=form.make.data,
            model=form.model.data,
            email=form.email.data,
        )
        db.session.add(new_enquiry)
        db.session.commit()
        return redirect(url_for("home.inventory"))
    vehicle = Vehicle.query.get_or_404(id)
    fuel_id = vehicle.fuel_type_id
    more_vehicles = (
        Vehicle.query.filter_by(make_id=vehicle.make_id)
        .order_by(Vehicle.createdAt.desc())
        .limit(3)
    )
    car_fuel_type = Fuel.query.filter_by(id=fuel_id).first_or_404()
    return render_template(
        "home/single_car_view.html",
        more_vehicles=more_vehicles,
        vehicle=vehicle,
        car_fuel_type=car_fuel_type,
        form=form
    )


@home.route("/contact_us", methods=["GET", "POST"])
def contact():
    form = ContactForm()

    if form.validate_on_submit():
        new_contact = Contact(
            name=form.name.data,
            phone_number=form.phone_number.data,
            message=form.message.data,
            subject=form.subject.data,
            email=form.email.data,
        )
        db.session.add(new_contact)
        db.session.commit()
        return redirect(url_for("home.index"))
    return render_template("home/contact_us.html", form=form)


@home.route("/blog")
def blog():
    return render_template("home/blog.html")


@home.route("/single_post")
def single_post():
    return render_template("home/single_post.html")


@home.route("/privacy_policy")
def privacy():
    return render_template("home/privacy_policy.html")


@home.route("/terms-of-use")
def terms_of_use():
    return render_template("home/terms_of_use.html")


@home.route("/terms-and-conditions")
def tour_operators_terms():
    return render_template("home/tour_operators_terms.html")

@home.route("/trade-in", methods=["GET","POST"])
@home.route("/sell_your_car", methods=["GET", "POST"])
def sell_vehicle():
    all_vehicles = Vehicle.query.all()
    """sell a vehicle."""
    form = SellVehicleForm()
    form.make.choices = [(row.id, row.name) for row in Make.query.all()]
    form.model.choices = [(row.id, row.name) for row in Model.query.all()]
    form.transmission.choices = [(row.id, row.type) for row in Transmission.query.all()]
    form.fuel_type.choices = [(row.id, row.type) for row in Fuel.query.all()]
    if form.validate_on_submit():
        make = Make.query.filter_by(id=form.make.data).first_or_404()
        model = Model.query.filter_by(id=form.model.data).first_or_404()
        transmission = Transmission.query.filter_by(
            id=form.transmission.data
        ).first_or_404()
        fuel = Fuel.query.filter_by(id=form.fuel_type.data).first_or_404()
        new_vehicle = SellersVehicle(
            name=form.name.data,
            price=form.price.data,
            description=form.description.data,
            plate=form.plate.data,
            year=form.year.data,
            mileage=form.mileage.data,
            color=form.color.data,
            condition=form.condition.data,
            seller_name=form.seller_name.data,
            seller_email=form.seller_email.data,
            phone_number=form.phone_number.data,
            area=form.area.data,
            model_id=model.id,
            make_id=make.id,

app/templates/home/_inventory.html
<div id="inventory" class="dealers-section product-type">
    <div class="dealers-section product-type">

        <h3 class="section-title">{{vehicles_count}} Vehicles</h3>

        <!-- dealer sorting -->

        <div class="flex-row flex-justify">

            <div class="sort-dealer">

                <div class="sort-col">

                    <div class="flex-row flex-center">

                        <span>Sort by</span>
                        <div class="auto-custom-select">
                            <select data-default-text="Price: highest first">
                                <option value="menu">Price: highest first</option>
                                <option value="menu">Price: lowest first</option>
                                <option value="menu">Mileage</option>
                                <option value="menu">Age (Newest)</option>
                                <option value="menu">New Stock</option>
                            </select>
                        </div>

                    </div>

                </div>


            </div>

        </div>

    </div>

    <div id="product-holder" class="products-holder view-list">

        <div class="row flex-row">
        {% for vehicle in all_vehicles %}
            <div class="col-sm-4 col-xs-6">

                <!-- - - - - - - - - - - - - - Product - - - - - - - - - - - - - - - - -->
                <div class="product">

                    <!-- - - - - - - - - - - - - - Product Image - - - - - - - - - - - - - - - - -->
                    <figure class="product-image">
                        <a href="{{ url_for('home.view_car', id=vehicle.id) }}"><img src="{% if vehicle.image_url %}
                            {{ url_for('static', filename='ckeditor_uploads/{}'.format(vehicle.image_url))}}
                       {% else %}
                            {{ url_for('static', filename='images/toyota.jpeg')}}
                       {% endif %}" alt=""></a>
                        <div class="overlay full-width-block">
                            <div class="icon-fancy">
                                <a href="{{ url_for('static', filename='ckeditor_uploads/{}'.format(vehicle.image_url))}}" class="fancybox" data-fancybox="group"><i
                                        class="licon-camera2"></i><span>7</span></a>
                                <a href="#"><i class="licon-camera"></i><span>1</span></a>
                            </div>
                            <div>
                                <a href="#"><i class="licon-heart"></i></a>
                                <a href="#"><i class="licon-copy"></i></a>
                            </div>
                        </div>
                    </figure>
                    <!-- - - - - - - - - - - - - - End of Product Image - - - - - - - - - - - - - - - - -->

                    <!-- - - - - - - - - - - - - - Product Description - - - - - - - - - - - - - - - - -->
                    <div class="product-description">

                        <div class="row">
                            <div class="col-xs-8">

                                <h5 class="product-name"><a href="{{ url_for('home.view_car', id=vehicle.id) }}">{{vehicle.name}}</a></h5>

                                <div class="pricing-area">

                                    <div class="product-price">
                                        {{'KSh {:,}'.format(vehicle.price)}}
                                    </div>

                                </div>
                                <div class="pricing-area">

                                    <div class="mpg">
                                        <span>Year</span>
                                        {{vehicle.year}}
                                    </div>
                                    <div class="mpg">
                                        <span>Mileage</span>
                                        {{vehicle.mileage}} km
                                    </div>
                                </div>
                                <div class="pricing-area">

                                    <div class="mpg">
                                        <span>Engine Size</span>
                                        {{vehicle.engine_size}} cc
                                    </div>
                                    <div class="mpg">
                                        <span>Engine Type</span>
                                        {% if vehicle.fuel_type_id==1 %} Petrol {% elif vehicle.fuel_type_id==2 %} Diesel
                                        {% elif vehicle.fuel_type_id==3 %} Hybrid {% else %} N/A {% endif %}
                                    </div>
                                </div>
                                <div class="pricing-area">
                                     <div class="mpg">
                                        <span>Transmission</span>
                                        {% if vehicle.transmission_id==1 %} Manual {% elif vehicle.transmission_id==2
                                       %} Automatic {% else %} N/A {% endif %}
                                    </div>
                                </div>


                                <p style="white-space: nowrap;text-overflow: ellipsis;overflow: hidden;">{{vehicle.description}}</p>

                                <div class="brends flex-row flex-center">
                                    <a href="#"><img src="" alt=""></a>
                                    <a href="#"><img src="" alt=""></a>
                                </div>

                            </div>
                            <div class="col-xs-4">

                                <div class="dealer-item">

                                    <div class="dealer-title">
                                        <img src="" alt="">
                                        <div class="wrapper">
                                            <a href="#"><b>Gigi Motors</b></a>
                                        </div>
                                    </div>

                                    <div class="dealer-desc">

                                        <div class="contact-section">



                                            <div class="contact-item">
                                                <span class="contact-title"><i
                                                        class="licon-telephone"></i>{{vehicle.phone_number}}</span>
                                            </div>

                                        </div>

                                        <a href="{{ url_for('home.view_car', id=vehicle.id) }}" class="btn btn-small">Enquire</a>

                                    </div>

                                    <a href="/buy_a_car?body_type={{vehicle.body_type}}" class="link-text2">Similar cars</a>

                                </div>

                            </div>
                        </div>

                    </div>
                    <!-- - - - - - - - - - - - - - End of Product Description - - - - - - - - - - - - - - - - -->

                </div>
                <!-- - - - - - - - - - - - - - / Product - - - - - - - - - - - - - - - - -->

            </div>
        {% else %}
          <div class="alert alert-warning">
            No cars found!!
          </div>
        {% endfor %}

        </div>

    </div>

    <ul class="pagination">
        <li>
          {% if prev_url %}
          <a href="{{ prev_url or '#' }}" class="prev-page"></a>
          {% endif %}
        </li>

        <li>
          {% if next_url %}
          <a href="{{ next_url or '#' }}" class="next-page {% if not next_url %} disabled{% endif %}"></a>
          {% endif %}
        </li>
    </ul>
</div>

app/templates/home/blank.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/home/contact_us.html
{% extends 'home/home_base.html' %}
{% block custom_head_tags %}
{{ super() }}
<style>
    #content {
        background: #fff
    }

    .mario {
        width: 33%;
        background: #fff;
        box-shadow: 0 2px 8px 0 rgba(5, 7, 15, .1);
        padding: 2rem 2rem;
    }

    .bh {
        border-left: 1px solid #000;
        padding-left: 30px;
        padding-right: 30px;
        margin-top: 25%;
    }

    .contact-item .contact-title i {
        font-size: 52px;
        vertical-align: 4px;
    }

    .contact-desc {
        display: block;
        padding-top: 10px;
    }

    [class*="btn"].btn-style-3 {
        background: #ed1c24 !important;
    }
</style>
{% endblock %}
{% block content %}
<!-- - - - - - - - - - - - - - Content - - - - - - - - - - - - - - - - -->

<div id="content">

    <!-- - - - - - - - - - - - - - Breadcrumbs - - - - - - - - - - - - - - - - -->

    <div class="breadcrumbs-wrap" data-bg="{{ url_for('static', filename='home/images/1920x200_img1.jpg') }}">

        <div class="container">

            <h1 class="page-title">Contact Us</h1>

            <ul class="breadcrumbs">

                <li><a href="{{ url_for('home.index') }}">Home</a></li>
                <li>Contact Us</li>

            </ul>

        </div>

    </div>

    <!-- - - - - - - - - - - - - end Breadcrumbs - - - - - - - - - - - - - - - -->


    <div class="page-section" data-bg="">

        <div class="container">
            <div class="mario">
                <h4 class="section-title mt-1">How can we help</h4>

                <div class="row">

                    <div class="col-md-12 col-sm-12">
                        {% for field in form.errors %}
                        {% for error in form.errors[field] %}
                        <div class="alert alert-error">
                            <strong>Error!</strong> {{error}}:{{field}}
                        </div>
                        {% endfor %}
                        {% endfor %}
                        <form class="contact-form style-2" method="post" action="">
                            {{ form.hidden_tag() }}

                            <div class="row">
                                <div class="col-sm-12">

                                    <label class="required">Your Name</label>
                                    {{ form.name(class='') }}
                                </div>
                                <div class="col-sm-12">
                                    <label class="required">Your email</label>
                                    {{ form.email(class='') }}

                                </div>
                                <div class="col-sm-12">

                                    <label class="required">Phone number</label>
                                    {{ form.phone_number(class='') }}
                                </div>
                                <div class="col-sm-12">
                                    <label class="required">Subject</label>
                                    {{ form.subject(class='') }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <label>Message</label>
                                    {{ form.message(class='', rows=5) }}


                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">

                                    {{ form.submit(class="btn btn-style-3") }}

                                </div>
                            </div>

                        </form>
                    </div>

                </div>
            </div>
        </div>
        

    </div>

    <div class="page-section">
        <div class="container">
            <div>
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="content-element7">

                            <div class="tabs tabs-section clearfix">

                                <!--tabs content-->
                                <div class="">
                                    <div id="tab-1">

                                        <div class="contact-section">
                                            <div class="col-md-4">
                                                <div class="contact-item">
                                                    <h4>Get In Touch</h4>
                                                </div>
                                            </div>
                                            <div class="col-md-1">
                                                <div class="contact-item bh">
                                                    <h6 class="contact-title"><i class="licon-map-marker"></i></h6>
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <span class="contact-desc">
                                                    Head Office: Hurlingham between Chaka Place and Nairobi Women's
                                                    Hospital,
                                                    Argwings Kodhek Road, Nairobi, Kenya</span>
                                                <span class="contact-desc">
                                                    Thika Road, Thika Road Mall (TRM), Second Floor, Nairobi</span>
                                            </div>
                                        </div>
                                        <div class="col-md-1">
                                            <div class="contact-item bh">
                                                <h6 class="contact-title"><i class="licon-telephone"></i></h6>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="contact-item">
                                                <span class="contact-desc"> 0726 310 490 - Hurlingham</span>
                                                <span class="contact-desc"> 0758 949 232 - Thika Road</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</div>
{% endblock %}