app/models/bookings.py
from datetime import datetime

from .. import db
from flask_moment import Moment


class Booking(db.Model):
    __tablename__ = 'bookings'
    id = db.Column(db.Integer, primary_key=True)
    listing_id = db.Column(db.Integer(), db.ForeignKey('listings.id'))
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'))
    status = db.Column(db.Boolean(), index=True, default=False)
    state = db.Column(db.String(120), default='pending')
    reason = db.Column(db.String(300), default='')
    timestamp = db.Column(db.DateTime(), default=datetime.utcnow)
    createdAt = db.Column(db.DateTime(), default=datetime.utcnow)
    updatedAt = db.Column(db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)
    # primary keys
    offers = db.relationship('Offer', backref='booking')
    orders = db.relationship('Order', backref='booking', uselist=False)

    def get_time(self):
        return self.createdAt

app/models/category.py
from datetime import datetime
from flask import current_app
from .. import db
from app.models.listings import Listing, listing_tags


class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.String(64), index=True)
    name = db.Column(db.String(64), index=True)
    image_url = db.Column(db.String(64), index=True)
    timestamp = db.Column(db.DateTime(), default=datetime.utcnow)
    createdAt = db.Column(db.DateTime(), default=datetime.utcnow)
    updatedAt = db.Column(db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)

    def get_count(self):
        data = Listing.query.join(
            listing_tags, (listing_tags.c.listing_id == Listing.id)).filter(
            listing_tags.c.category_id == self.id).filter(Listing.status == True)
        return data.count()


def get_categories(data, page):
    list = []
    for field in [(row.name) for row in Category.query.all()]:
        if field in data:
            list.append(int(data[field]))
    listings = Listing.query.filter(Listing.status == True).order_by(Listing.createdAt.desc()).paginate(page,
                                                                                                        current_app.config[
                                                                                                            'POSTS_PER_PAGE'],
                                                                                                        False)
    if list:
        listings = Listing.query.join(
            listing_tags, (listing_tags.c.listing_id == Listing.id)).filter(
            listing_tags.c.category_id.in_(list)).filter(Listing.status == True).order_by(
            Listing.createdAt.desc()).paginate(page, current_app.config['POSTS_PER_PAGE'], False)
    return listings

app/models/listings.py
from datetime import datetime
from app.models.bookings import Booking
from app.models.places import Place
from app.models.prices import Price
from sqlalchemy import or_, and_
from flask import current_app
from .. import db
from .reviews import Review
from sqlalchemy.ext.hybrid import hybrid_method

listing_tags = db.Table('listing_tags',
                        db.Column('listing_id', db.Integer, db.ForeignKey('listings.id')),
                        db.Column('category_id', db.Integer, db.ForeignKey('categories.id')))


class Listing(db.Model):
    __tablename__ = 'listings'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), default='')
    short_description = db.Column(db.String(320), default='')
    long_description = db.Column(db.String(2000), default='')
    publisher_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    location = db.Column(db.String(80), index=True)
    duration = db.Column(db.Integer)
    package = db.Column(db.String(64), index=True)
    rating = db.Column(db.Integer(), default=0)
    overal_ratings = db.Column(db.Integer(), default=0)
    connectivity = db.Column(db.String(120))
    physical_condition = db.Column(db.String(64))
    price_type_id = db.Column(db.Integer(), db.ForeignKey('prices.id'))
    availability_from = db.Column(db.DateTime(), default=datetime.utcnow, index=True)
    availability_to = db.Column(db.DateTime(), default=datetime.utcnow, index=True)
    feature_id = db.Column(db.Integer, db.ForeignKey('features.id'))
    add_ons = db.Column(db.String(2000), default='')
    policy = db.Column(db.String(2000), default='')
    status = db.Column(db.Boolean(), index=True, default=False)
    published = db.Column(db.Boolean(), index=True, default=False)
    space = db.Column(db.Integer())

    # Relationships
    bookings = db.relationship('Booking', backref='listing', lazy='dynamic')
    reviews = db.relationship('Review', backref='listing', lazy='dynamic')
    images = db.relationship('Image', backref='listing', lazy='dynamic')
    activities = db.relationship('Activity', backref='listing', lazy='dynamic')
    places = db.relationship('Place', backref='listing', lazy='dynamic')
    days = db.relationship('Day', backref='listing', lazy='dynamic')
    categories = db.relationship('Category', secondary=listing_tags, backref='listings', lazy='dynamic')

    timestamp = db.Column(db.DateTime(), default=datetime.utcnow)
    createdAt = db.Column(db.DateTime(), default=datetime.utcnow)
    updatedAt = db.Column(db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)

    def get_bookings_count(self):
        count = Booking.query.filter_by(listing_id=self.id).count()
        return count

    def get_listings(self):
        return Review.query.filter_by(listing_id=self.id)

    def get_make_count(self):
        data = Listing.query.filter_by(publisher=self.publisher, location=self.location).count()
        return data

    @hybrid_method
    def child_count(self):
        return len([_child for _child in self.bookings])


def get_search(name, date, page):
    if name != '':
        first = Listing.query.filter(db.false())
        list = [(row.listing_id) for row in Place.query.filter(Place.place.like('%' + name.lower() + '%')).all()]
        if list:
            first = Listing.query.filter(Listing.id.in_(list)).filter(Listing.availability_to > date).filter(Listing.status == True)
        own = Listing.query.filter(
            and_(Listing.location.like('%' + name.capitalize() + '%'), Listing.availability_to > date)).filter(Listing.status == True)
        listings = first.union(own).order_by(Listing.rating.desc()).paginate(page,
                                                                                current_app.config['POSTS_PER_PAGE'],
                                                                                False)
    else:
        listings = Listing.query.filter(Listing.availability_to > date).filter(Listing.status == True).order_by(Listing.rating.desc()).paginate(
            page, current_app.config['POSTS_PER_PAGE'], False)

    return listings


def get_range(maxval, minval, page):
    listings = Listing.query.filter(db.false())
    list = [(row.id) for row in
            Price.query.filter(and_(Price.total_price_adults <= maxval, Price.total_price_adults >= minval)).all()]
    if list:
        listings = Listing.query.filter(Listing.price_type_id.in_(list)).filter(Listing.status == True)
    return listings.order_by(Listing.createdAt.desc()).paginate(page, current_app.config['POSTS_PER_PAGE'], False)


def get_ratings(data, page):
    list = []
    for field in ['first', 'second', 'third', 'fourth', 'fifth']:
        if field in data:
            list.append(int(data[field]))
    listings = Listing.query.filter(Listing.status == True)
    if list:
        listings = Listing.query.filter(Listing.rating.in_(list)).filter(Listing.status == True)
    return listings.order_by(Listing.createdAt.desc()).paginate(page, current_app.config['POSTS_PER_PAGE'], False)

app/home/views.py
from flask import Blueprint, render_template, redirect, url_for, jsonify, flash
from flask_login import current_user, login_required
from datetime import datetime, date
from app.models import *
from app.home.forms import *
from sqlalchemy import or_, and_, func

home = Blueprint("home", __name__)


@home.route("/", methods=["post", "get"])
def index():
    """Admin dashboard page."""
    all_vehicles = Vehicle.query.order_by(Vehicle.createdAt.desc()).limit(8)
    featured_vehicles = Vehicle.query.filter_by(featured=True).limit(8)
    form = SearchForm()
    make = [(row.id, row.name) for row in Make.query.all()]
    model = [(row.id, row.name) for row in Model.query.all()]
    transmission = [(row.id, row.type) for row in Transmission.query.all()]
    fuel = [(row.id, row.type) for row in Fuel.query.all()]
    year_to = [(i, i) for i in list(reversed(range(2000, date.today().year+1)))]
    year_from = [(i, i) for i in list(range(2000, date.today().year+1))]
    make.insert(0, (0, "--All Makes--"))
    year_from.insert(0, (0, "Year from"))
    year_to.insert(0, (0, "Year to"))
    model.insert(0, (0, "Model"))
    transmission.insert(0, (0, "Transmission"))
    fuel.insert(0, (0, "Fuel Type"))
    form.year_from.choices = year_from
    form.year_to.choices = year_to
    form.make.choices = make
    form.model.choices = model
    form.transmission.choices = transmission
    form.fuel.choices = fuel
    return render_template(
        "home/index.html",
        all_vehicles=all_vehicles,
        featured_vehicles=featured_vehicles,
        form=form,
        car_makes=Make.query.all(),
    )


@home.route("/buy_a_car", methods=["post", "get"])
def inventory():
    """all vehicles."""
    page = request.args.get("page", 1, type=int)
    year_from = request.args.get("year_from", 0, type=int)
    year_to = request.args.get("year_to", 0, type=int)
    make = request.args.get("make", 0, type=int)
    model = request.args.get("model", 0, type=int)
    fuel = request.args.get("fuel", 0, type=int)
    transmission = request.args.get("transmission", 0, type=int)
    body_type = request.args.get("body_type", "", type=str)

    makes = [(row.id, row.name) for row in Make.query.all()]
    transmissions = [(row.id, row.type) for row in Transmission.query.all()]
    fuel_types = [(row.id, row.type) for row in Fuel.query.all()]
    years = list(reversed(range(2000, date.today().year+1)))

    all_vehicles = (
        Vehicle.query.filter(
            Vehicle.year >= year_from if year_from else Vehicle.id.isnot(None)
        )
        .filter(Vehicle.year <= year_to if year_to else Vehicle.id.isnot(None))
        .filter(Vehicle.make_id == make if make else Vehicle.id.isnot(None))
        .filter(Vehicle.model_id == model if model else Vehicle.id.isnot(None))
        .filter(
            Vehicle.transmission_id == transmission
            if transmission
            else Vehicle.id.isnot(None)
        )
        .filter(Vehicle.body_type == body_type if body_type else Vehicle.id.isnot(None))
        .filter(Vehicle.fuel_type_id == fuel if fuel else Vehicle.id.isnot(None))
        .order_by(Vehicle.createdAt.desc())
        .paginate(page, current_app.config["POSTS_PER_PAGE"], False)
    )
    next_url = (
        url_for("home.inventory", page=all_vehicles.next_num)
        if all_vehicles.has_next
        else None
    )
    prev_url = (
        url_for("home.inventory", page=all_vehicles.prev_num)
        if all_vehicles.has_prev
        else None
    )
    total_vehicles = Vehicle.query.order_by(Vehicle.createdAt.desc()).all()
    vehicles_count = len(all_vehicles.items)
    max_price = int(max(node.price for node in total_vehicles)) if total_vehicles else 0
    min_price = int(min(node.price for node in total_vehicles)) if total_vehicles else 0
    return render_template(
        "home/inventory.html",
        all_vehicles=all_vehicles.items,
        vehicles_count=vehicles_count,
        next_url=next_url,
        prev_url=prev_url,
        max_price=max_price,
        min_price=min_price,
        makes=makes,
        transmissions=transmissions,
        years=years,
        fuel_types=fuel_types,
    )


@home.route("/_get_cars/", methods=["POST"])
def _get_cars():
    page = request.args.get("page", 1, type=int)
    data = request.get_json() or {}
    if (
        "years" not in data
        or "makes" not in data
        or "models" not in data
        or "bodyTypes" not in data
        or "transmissions" not in data
        or "min_price" not in data
        or "max_price" not in data
    ):
        return "", 404
    all_vehicles = (
        Vehicle.query.filter(
            Vehicle.year.in_(data["years"])
            if len(data["years"])
            else Vehicle.id.isnot(None)
        )
        .filter(
            Vehicle.make_id.in_(data["makes"])
            if len(data["makes"])
            else Vehicle.id.isnot(None)
        )
        .filter(
            Vehicle.model_id.in_(data["models"])
            if len(data["models"])
            else Vehicle.id.isnot(None)
        )
        .filter(
            Vehicle.body_type.in_(data["bodyTypes"])
            if len(data["bodyTypes"])
            else Vehicle.id.isnot(None)
        )
        .filter(
            Vehicle.transmission_id.in_(data["transmissions"])
            if len(data["transmissions"])
            else Vehicle.id.isnot(None)
        )
        .filter(
            Vehicle.price >= data["min_price"]
            if data["min_price"]
            else Vehicle.id.isnot(None)
        )
        .filter(
            Vehicle.price <= data["max_price"]
            if data["max_price"]
            else Vehicle.id.isnot(None)
        )
        .order_by(Vehicle.createdAt.desc())
        .paginate(page, current_app.config["POSTS_PER_PAGE"], False)
    )
    next_url = (
        url_for("home.inventory", page=all_vehicles.next_num)
        if all_vehicles.has_next
        else None
    )
    prev_url = (
        url_for("home.inventory", page=all_vehicles.prev_num)
        if all_vehicles.has_prev
        else None
    )
    return render_template(
        "home/_inventory.html",
        all_vehicles=all_vehicles.items,
        vehicles_count=len(all_vehicles.items),
        next_url=next_url,
        prev_url=prev_url,
    )


@home.route("/view_car/<id>", methods=["post", "get"])
def view_car(id):
    """Admin dashboard page."""
    form = EnquiryForm()
    if form.validate_on_submit():
        new_enquiry = SingleEnquiry(
            name=form.name.data,
            phone_number=form.phone_number.data,
            message=form.message.data,
            plate=form.plate.data,
            year=form.year.data,
            budget=form.budget.data,
            make=form.make.data,
            model=form.model.data,
            email=form.email.data,
        )
        db.session.add(new_enquiry)
        db.session.commit()
        return redirect(url_for("home.inventory"))
    vehicle = Vehicle.query.get_or_404(id)
    fuel_id = vehicle.fuel_type_id
    more_vehicles = (
        Vehicle.query.filter_by(make_id=vehicle.make_id)
        .order_by(Vehicle.createdAt.desc())
        .limit(3)
    )
    car_fuel_type = Fuel.query.filter_by(id=fuel_id).first_or_404()
    return render_template(
        "home/single_car_view.html",
        more_vehicles=more_vehicles,
        vehicle=vehicle,
        car_fuel_type=car_fuel_type,
        form=form
    )


@home.route("/contact_us", methods=["GET", "POST"])
def contact():
    form = ContactForm()

    if form.validate_on_submit():
        new_contact = Contact(
            name=form.name.data,
            phone_number=form.phone_number.data,
            message=form.message.data,
            subject=form.subject.data,
            email=form.email.data,
        )
        db.session.add(new_contact)
        db.session.commit()
        return redirect(url_for("home.index"))
    return render_template("home/contact_us.html", form=form)


@home.route("/blog")
def blog():
    return render_template("home/blog.html")


@home.route("/single_post")
def single_post():
    return render_template("home/single_post.html")


@home.route("/privacy_policy")
def privacy():
    return render_template("home/privacy_policy.html")


@home.route("/terms-of-use")
def terms_of_use():
    return render_template("home/terms_of_use.html")


@home.route("/terms-and-conditions")
def tour_operators_terms():
    return render_template("home/tour_operators_terms.html")

@home.route("/trade-in", methods=["GET","POST"])
@home.route("/sell_your_car", methods=["GET", "POST"])
def sell_vehicle():
    all_vehicles = Vehicle.query.all()
    """sell a vehicle."""
    form = SellVehicleForm()
    form.make.choices = [(row.id, row.name) for row in Make.query.all()]
    form.model.choices = [(row.id, row.name) for row in Model.query.all()]
    form.transmission.choices = [(row.id, row.type) for row in Transmission.query.all()]
    form.fuel_type.choices = [(row.id, row.type) for row in Fuel.query.all()]
    if form.validate_on_submit():
        make = Make.query.filter_by(id=form.make.data).first_or_404()
        model = Model.query.filter_by(id=form.model.data).first_or_404()
        transmission = Transmission.query.filter_by(
            id=form.transmission.data
        ).first_or_404()
        fuel = Fuel.query.filter_by(id=form.fuel_type.data).first_or_404()
        new_vehicle = SellersVehicle(
            name=form.name.data,
            price=form.price.data,
            description=form.description.data,
            plate=form.plate.data,
            year=form.year.data,
            mileage=form.mileage.data,
            color=form.color.data,
            condition=form.condition.data,
            seller_name=form.seller_name.data,
            seller_email=form.seller_email.data,
            phone_number=form.phone_number.data,
            area=form.area.data,
            model_id=model.id,
            make_id=make.id,

app/templates/publisher/_profile_modal.html
{% extends 'layouts/base.html' %}
{% block custom_head_tags %}
   {{ super() }}

{% endblock %}
{% block content %}
 <!-- START CONTENT -->
    <section id="content">
          <!--start container-->
          <div class="container">
            <div class="section">
              <div class="divider"></div>
              <ul id="profile-page-about-feed" class="collection z-depth-1">
                <li class="collection-item avatar">
                  <img src="{{ user.avatar(80) }}" alt="" class="circle deep-orange accent-2">
                  <span class="title">Name</span>
                  <p>{{ user.full_name() }}
                  </p>
                </li>
                <li class="collection-item avatar">
                  <i class="material-icons circle teal accent-4">contact_mail</i>
                  <span class="title">Email</span>
                  <p>{{ user.email }}
                  </p>
                </li>
                <li class="collection-item avatar">
                  <i class="material-icons circle cyan">location_city</i>
                  <span class="title">Address</span>
                  <p>{{ user.address }}
                  </p>
                </li>

              </ul>
            </div>
          </div>
          <!--end container-->

        </section>
          <div id='profile-placehold'>
          </div>
<!-- END CONTENT -->
{% endblock%}

app/templates/publisher/bookings.html
{% extends 'layouts/base.html' %}
{% block custom_head_tags %}
   {{ super() }}

{% endblock %}
{% block content %}
 <!-- START CONTENT -->
    <section id="content">
          <!--start container-->
          <div class="container">
            <div class="section">
              <div class="divider"></div>
              <!--DataTables example-->
              <div id="table-datatables">
                <h4 class="header">Bookings</h4>
                <div class="row">
                  <div class="col s12">
                    <div id="placehold">
                    {% include 'publisher/_bookings.html' %}
                  </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--end container-->

        </section>
          <div id='profile-placehold'>
          </div>
<!-- END CONTENT -->
{% endblock%}

app/templates/publisher/edit_profile.html
{% extends 'layouts/base.html' %}
{% block content %}
       <!-- START CONTENT -->
        <section id="content">
          <!--breadcrumbs start-->
          <div id="breadcrumbs-wrapper">
            <div class="container">
              <div class="row">
                <div class="col s10 m6 l6">
                  <h5 class="breadcrumbs-title">Edit Profile</h5>
                  <ol class="breadcrumbs">
                    <li><a href="{{url_for('publisher.dashboard')}}">Dashboard</a></li>
                    <li><a href="{{url_for('publisher.profile')}}">Profile</a></li>
                    <li class="active">Edit</li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
          <!--breadcrumbs end-->

          <!--start container-->
          <div class="container">
            <div class="section">
              <div class="divider"></div>
                <div class="row">
                <div class="col s12 m12 l12">
                  <div class="card-panel">
                    <h4 class="header2">Company Information</h4>
                    <div class="row">
                      <form class="col s12" method="post" enctype="multipart/form-data">
                        {{ form.hidden_tag() }}

                        <div class="row">
                          <div class="input-field col s12">
                            <i class="material-icons prefix">account_balance</i>
                            {{ form.company_name() }}
                            <label for="first_name">Company Name</label>
                            {%for error in form.company_name.errors%}
                                <div class="error">{{ error }}</div>
                              {%endfor%}
                          </div>
                          <div class="input-field col s6">
                            <i class="material-icons prefix">payment</i>
                            {{ form.paypal() }}
                            <label for="email">Paypal Email</label>
                            {%for error in form.paypal.errors%}
                                <div class="error">{{ error }}</div>
                              {%endfor%}
                          </div>
                          <div class="input-field col s6">
                            <i class="material-icons prefix">link</i>
                            {{ form.facebook() }}
                            <label for="email">Facebook url</label>
                            {%for error in form.facebook.errors%}
                                <div class="error">{{ error }}</div>
                              {%endfor%}
                          </div>
                          <div class="input-field col s6">
                            <i class="material-icons prefix">link</i>
                            {{ form.twitter() }}
                            <label for="email">Twitter url</label>
                            {%for error in form.twitter.errors%}
                                <div class="error">{{ error }}</div>
                              {%endfor%}
                          </div>
                          <div class="input-field col s6">
                            <i class="material-icons prefix">link</i>
                            {{ form.instagram() }}
                            <label for="email">Instagram url</label>
                            {%for error in form.instagram.errors%}
                                <div class="error">{{ error }}</div>
                              {%endfor%}
                          </div>
                        </div>
                        <div class="row">
                          <div class="input-field col s12">
                            <i class="material-icons prefix">note</i>
                            {{ form.overview(class="materialize-textarea") }}
                            <label for="email">Overview</label>
                            {%for error in form.overview.errors%}
                                <div class="error">{{ error }}</div>
                              {%endfor%}
                          </div>
                        </div>
                        <div class="row" data-toggle="fieldset" id="phone-fieldset">
                          {%  for phone in form.phones %}
                          <div class="row" data-toggle="fieldset-entry">
                          <div class="input-field col s10">
                            <i class="material-icons prefix">phone</i>
                            {{ phone.phone_number() }}
                            <label for="email">Phone Number</label>
                            {%for error in phone.phone_number.errors%}
                                <div class="error">{{ error }}</div>
                              {%endfor%}
                          </div>
                          <div class="input-field col s2">
                            <button type="button" class="btn-floating waves-effect waves-light red accent-2" data-toggle="fieldset-remove-row" id="phone-{{loop.index0}}-remove">
                              <i class="material-icons">remove</i>
                              </button>
                          </div>
                        </div>
                          {% endfor %}
                          <div class="row">
                            <div class="center-align">
                              <button style="margin-left:3%" type="button" data-toggle="fieldset-add-row" class="btn-floating waves-effect waves-light green accent-2 left" data-target="#phone-fieldset">
                                <i class="material-icons">add</i>
                              </button>
                            </div>
                          </div>
                        </div>
                        <div class="row" data-toggle="fieldset" id="place-fieldset">
                          {%  for email in form.emails %}
                          <div class="row" data-toggle="fieldset-entry">
                          <div class="input-field col s10">
                            <i class="material-icons prefix">email</i>
                            {{ email.email() }}
                            <label for="email">Emails</label>
                            {%for error in email.email.errors%}
                                <div class="error">{{ error }}</div>
                              {%endfor%}
                          </div>
                          <div class="input-field col s2">
                            <button type="button" class="btn-floating waves-effect waves-light red accent-2" data-toggle="fieldset-remove-row" id="place-{{loop.index0}}-remove">
                              <i class="material-icons">remove</i>
                              </button>
                          </div>
                        </div>
                          {% endfor %}
                          <div class="row">
                            <div class="center-align">
                              <button style="margin-left:3%" type="button" data-toggle="fieldset-add-row" class="btn-floating waves-effect waves-light green accent-2 left" data-target="#place-fieldset">
                                <i class="material-icons">add</i>
                              </button>
                            </div>
                          </div>
                        </div>
                        <div class="row" data-toggle="fieldset" id="day-fieldset">
                          {%  for location in form.locations %}
                          <div class="row" data-toggle="fieldset-entry">
                          <div class="input-field col s5">
                            <i class="material-icons prefix">location_on</i>
                            {{ location.city() }}
                            <label for="email">City</label>
                            {%for error in location.city.errors%}
                                <div class="error">{{ error }}</div>
                              {%endfor%}
                          </div>
                          <div class="input-field col s5">
                            <i class="material-icons prefix">location_on</i>
                           {{ location.make }}
                            <label for="email">make</label>
                            {%for error in location.make.errors%}
                                <div class="error">{{ error }}</div>
                              {%endfor%}
                          </div>
                          <div class="input-field col s2">
                            <button type="button" class="btn-floating waves-effect waves-light red accent-2" data-toggle="fieldset-remove-row" id="day-{{loop.index0}}-remove">
                              <i class="material-icons">remove</i>
                              </button>
                          </div>
                        </div>
                          {% endfor %}
                          <div class="row">
                            <div class="center-align">
                              <button style="margin-left:3%" type="button" data-toggle="fieldset-add-row" class="btn-floating waves-effect waves-light green accent-2 left" data-target="#day-fieldset">
                                <i class="material-icons">add</i>
                              </button>
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="center-align">
                            <div class="input-field col s12">
                              {{ form.terms_of_use() }}
                              <label for="">
                                Accept <a href="{{ url_for('home.tour_operators_terms')}}" target="_blank">Terms and Conditions</a>
                              </label>
                              {%for error in form.paypal.errors%}
                                  <div class="error">{{ error }}</div>
                                {%endfor%}
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="row">
                            <div class="center-align">
                              <button class="btn cyan waves-effect waves-light" type="submit">Submit
                                <i class="material-icons right">send</i>
                              </button>
                            </div>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--end container-->
        </section>
        <!-- END CONTENT -->
{% endblock%}

{% block scripts %}
   <script src="{{ url_for("static", filename="js/page.js") }}"></script>
{% endblock %}